### PR TITLE
Optimisations and Fixes for Eager Evaluation bug.

### LINKED ISSUE #161: Unable to view all patients upon clicking button.
Before 

onduty command, the patients were searched for 111111111. Then after doctor screen and returning to patients screen, it is blank.

Maybe it is still returning the previous search state

<hr><sub>[original: sreesubbash/ped#9]<br/>
</sub>

### PR DESCRIPTION
**Pull request by CarbonGrid**
# STATUS
1. Improved display for exceeding content in OmniPanel.
2. LogicManager now resets last eager evaluated model.
3. Eager Evaluation no longer waits for AutoCompleter before it starts.
4. Adds menu items for "Check for Updates" & "About Us".

Fixes #161.

### CODE REVIEW

File: src/main/java/seedu/address/logic/LogicManager.java [hunk 1]
```diff
@@ -87,9 +88,22 @@ public synchronized CommandResult execute(String commandText)
     @Override
     public synchronized void eagerEvaluate(String commandText, Consumer<String> displayResult) {
         final Command command = addressBookParser.eagerEvaluateCommand(commandText);
+        String currCommandWord = commandText.substring(0, commandText.indexOf(' ') + 1);
+        if (!lastCommandWord.equals(currCommandWord)) {
+            displayResult.accept("");
+            try {
+                this.execute(lastCommandWord);
+            } catch (CommandException | ParseException e) {
+                // do nothing
```
Comment (SakuraBlossom) [inline src/main/java/seedu/address/logic/LogicManager.java]: Please avoid having empty catch blocks. Atleast log the exception.
